site_name: Gestão VSM
site_url: https://mydomain.org/mysite
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
  palette: 
    # Palette toggle for light mode
    - scheme: default
      accent: black
      primary: black
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      accent: black
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home: index.md
  - Visão de Produto e Projeto: visao_prod_proj.md
  - Apresentações e Entregas: 
    - apresentacoes_entregas/apresentacao_1.md